[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
via_ir = true
optimizer = true
optimizer_runs = 200
# Allow vm.writeFile for deployment scripts (e.g. .dao_library_addresses, .dao_library_addresses.env)
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
